package ai.chat2db.plugin.redis.constant;

import java.util.regex.Pattern;

public final class RedisConstants {

    public static final String COMMAND_CONFIG = "config";
    public static final String COMMAND_CONFIG_GET_DATABASES = COMMAND_CONFIG + " get databases";
    public static final String COMMAND_ARGUMENT_SEPARATOR = " ";
    public static final String COMMAND_LINE_SEPARATOR = "\n";
    public static final String COMMAND_DELETE_KEY_PREFIX = "DEL ";
    public static final String COMMAND_DELETE_TABLE_PREFIX = "del ";
    public static final String COMMAND_EXISTS_KEY = "EXISTS %s";
    public static final String COMMAND_EXPIRE_ARGUMENT_PREFIX = " EX ";
    public static final String COMMAND_EXPIRE_KEY_PREFIX = "EXPIRE ";
    public static final String COMMAND_PERSIST_KEY_PREFIX = "PERSIST ";
    public static final String COMMAND_GET_KEY_PREFIX = "GET ";
    public static final String COMMAND_HASH_DELETE_PREFIX = "HDEL ";
    public static final String COMMAND_HASH_GET_ALL_PREFIX = "HGETALL ";
    public static final String COMMAND_HASH_GET_PREFIX = "HGET ";
    public static final String COMMAND_HASH_SET_PREFIX = "HSET ";
    public static final String COMMAND_LIST_INSERT_AFTER_FRAGMENT = " AFTER ";
    public static final String COMMAND_LIST_INSERT_PREFIX = "LINSERT ";
    public static final String COMMAND_LIST_PUSH_PREFIX = "LPUSH ";
    public static final String COMMAND_LIST_RIGHT_PUSH_PREFIX = "RPUSH ";
    public static final String COMMAND_LIST_RANGE_ALL_SUFFIX = " 0 -1";
    public static final String COMMAND_LIST_RANGE_PREFIX = "LRANGE ";
    public static final String COMMAND_LIST_REMOVE_ONE_FRAGMENT = " 1 ";
    public static final String COMMAND_LIST_REMOVE_PREFIX = "LREM ";
    public static final String COMMAND_SCAN_ALL_LIMIT_20 = "scan 0 MATCH * COUNT 20";
    public static final String COMMAND_SCAN_ALL_LIMIT_1000 = "scan 0 MATCH * COUNT 1000";
    public static final String COMMAND_SCAN_PATTERN = "scan %s MATCH *%s* COUNT 50";
    public static final String COMMAND_SELECT_DATABASE_PREFIX = "select ";
    public static final String COMMAND_SET_ADD_PREFIX = "SADD ";
    public static final String COMMAND_SET_KEY_IF_EXISTS_SUFFIX = " XX \n";
    public static final String COMMAND_SET_KEY_PREFIX = "SET ";
    public static final String COMMAND_SET_MEMBERS_PREFIX = "SMEMBERS ";
    public static final String COMMAND_SET_REMOVE_PREFIX = "SREM ";
    public static final String COMMAND_STREAM_ADD_PREFIX = "XADD ";
    public static final String COMMAND_STREAM_DELETE_PREFIX = "XDEL ";
    public static final String COMMAND_STREAM_RANGE_PREFIX = "XRANGE ";
    public static final String COMMAND_STREAM_RANGE_SUFFIX = " - + COUNT 10000";
    public static final String COMMAND_TTL_KEY = "TTL %s";
    public static final String COMMAND_TYPE_KEY = "type %s";
    public static final String COMMAND_ZSET_ADD_PREFIX = "ZADD ";
    public static final String COMMAND_ZSET_RANGE_PREFIX = "ZRANGE ";
    public static final String COMMAND_ZSET_RANGE_WITH_SCORES_SUFFIX = " 0 -1 WITHSCORES";
    public static final String COMMAND_ZSET_REMOVE_PREFIX = "ZREM ";
    public static final String JDBC_REDIS_URL_PREFIX = "jdbc:redis://";
    public static final String CONFIG_GET_PERMISSION_ERROR = "config|get";
    public static final String CONFIG_PERMISSION_ERROR = "no permissions to run the 'config";
    public static final String DEFAULT_DATABASE = "0";
    public static final String SCAN_INITIAL_CURSOR = "0";
    public static final String ERROR_SQL_ANALYSIS = "dataSource.sqlAnalysisError";
    public static final String ERROR_SQL_MUST_NOT_BE_NULL = "SQL must not be null";
    public static final String ERROR_UNSUPPORTED_SQL_BUILDER_METHOD_PREFIX = "Redis SQL builder does not support ";
    public static final String ERROR_UNSUPPORTED_KEY_TYPE = "Redis key type '%s' is not supported; valid types are string, list, set, zset, hash, stream.";
    public static final String FIELD_FIELD = "field";
    public static final String FIELD_FIELDS = "fields";
    public static final String FIELD_ID = "id";
    public static final String FIELD_KEY = "key";
    public static final String FIELD_KEY_TYPE = "keyType";
    public static final String FIELD_SCORE = "score";
    public static final String FIELD_TTL = "ttl";
    public static final String FIELD_VALUE = "value";
    public static final String LOG_EXECUTE = "execute:{}";
    public static final String LOG_EXECUTE_UPDATE_ERROR = "executeUpdate error sql:{}";
    public static final String METHOD_BUILD_AI_TABLE_SCHEMA = "buildAITableSchema";
    public static final String METHOD_BUILD_ALTER_DATABASE = "buildAlterDatabase";
    public static final String METHOD_BUILD_ALTER_SCHEMA = "buildAlterSchema";
    public static final String METHOD_BUILD_ALTER_TABLE = "buildAlterTable";
    public static final String METHOD_BUILD_ALTER_VIEW = "buildAlterView";
    public static final String METHOD_BUILD_BATCH_INSERT = "buildBatchInsert";
    public static final String METHOD_BUILD_CREATE_DATABASE = "buildCreateDatabase";
    public static final String METHOD_BUILD_CREATE_SCHEMA = "buildCreateSchema";
    public static final String METHOD_BUILD_CREATE_TABLE = "buildCreateTable";
    public static final String METHOD_BUILD_CREATE_VIEW = "buildCreateView";
    public static final String METHOD_BUILD_DELETE = "buildDelete";
    public static final String METHOD_BUILD_DROP_DATABASE = "buildDropDatabase";
    public static final String METHOD_BUILD_DROP_SCHEMA = "buildDropSchema";
    public static final String METHOD_BUILD_DROP_TABLE = "buildDropTable";
    public static final String METHOD_BUILD_DROP_VIEW = "buildDropView";
    public static final String METHOD_BUILD_EXPLAIN = "buildExplain";
    public static final String METHOD_BUILD_INSERT = "buildInsert";
    public static final String METHOD_BUILD_ORDER_BY = "buildOrderBy";
    public static final String METHOD_BUILD_PAGE_LIMIT = "buildPageLimit";
    public static final String METHOD_BUILD_SELECT_COUNT = "buildSelectCount";
    public static final String METHOD_BUILD_SELECT_TABLE = "buildSelectTable";
    public static final String METHOD_BUILD_SHOW_CREATE_VIEW = "buildShowCreateView";
    public static final String METHOD_BUILD_TRUNCATE_TABLE = "buildTruncateTable";
    public static final String METHOD_BUILD_UPDATE = "buildUpdate";
    public static final String METHOD_BUILD_USE_DATABASE = "buildUseDatabase";
    public static final String REDIS_EXEC_COMMAND = "EXEC";
    public static final String REDIS_MULTI_COMMAND = "MULTI \n";
    public static final String REDIS_DATABASE_IN_URL_REGEX = "/([^/?#]*)";
    public static final Pattern REDIS_DATABASE_IN_URL_PATTERN = Pattern.compile(REDIS_DATABASE_IN_URL_REGEX);
    public static final String SQL_RENAME_KEY_PREFIX = "RENAME ";
    public static final String UNKNOWN_COMMAND_ERROR = "unknown command";
    public static final String SELECT_DATABASE_OUT_OF_RANGE_ERROR = "db index is out of range";
    public static final String SELECT_COMMAND_ERROR = "select";
    public static final String OUT_OF_RANGE_ERROR = "out of range";
    public static final int MAX_DATABASE_PROBE_COUNT = 256;
    public static final int CONFIG_DATABASES_VALUE_INDEX = 2;

    private RedisConstants() {
    }
}
